name: Update PR size and stability labels
on:
  pull_request:
    branches: [ master, main ]
    types: [ opened, synchronize, closed, reopened ]
jobs:
  pr-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: devrating/pr-size-advisor@a8eca5b4f59c16b7575303fba7d8758b09a280a4
