name: Update PR size suggestions at devrating.net
on:
  pull_request:
jobs:
  devrating:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-docker-action@master
      with:
        who-to-greet: 'Mona the Octocat'
